name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: List Files
      run: dir /s  # This will print all files to the logs so we can see where the .sln is

    - name: Restore dependencies
      run: nuget restore CyberBot_POE.sln

    - name: Build
      run: msbuild CyberBot_POE.sln /p:Configuration=Release
