name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Restore dependencies
      run: nuget restore CyberBot_POE.sln
      
    - name: Build
      run: msbuild CyberBot_POE.sln /p:Configuration=Release
